import { Injectable } from '@nestjs/common';
import { AppLoggerService } from '../../../common/utils-service/logger.service';
import { ActionGetResponseDto } from '../dto/action.output.dto';
import { AppConfigService } from '../../../common/utils-service/app.config.services';
import { MysteryBoxDbService } from '../../../modules/db/mystery-boxs.service';
import { MysteryBoxEntity, MysteryBoxStatus } from '../../../database/entities/mystery-boxs.entity';
import Decimal from 'decimal.js';
import { MoreThanOrEqual } from 'typeorm';
import { LAMPORTS_PER_SOL } from '@solana/web3.js';
import { GrabTransactionStatus } from '../../../database/entities/grab-mystery-boxs.entity';
import { calculateBounty, calculatePlayerReward, formatCountdown, shortenAddress } from '../../../common/utils/tools';

@Injectable()
export class ActionService {
    constructor(private readonly logger: AppLoggerService, private readonly appConfig: AppConfigService, private readonly mysteryBoxDbService: MysteryBoxDbService) {
        this.logger.setContext(ActionService.name);
    }
    createMysteryBoxAction(): ActionGetResponseDto {
            const payload = {
                icon: 'https://storage.bombfun.com/container-1.png',
                label: 'Create',
                title: 'Bomb Fun',
                description: '💰 or 💣? Get lucky with bombfun.com\n\n' +
                    '😈 90% chance on 💰 and 10% on 💣?\n\n' +
                    '📝 Create: Enter a bomb number and amount to create a bomb box.\n\n' +
                    '🏆 Rule: If the last digit of the drawn amount matches the bomb number, the player pays 1.8x. Otherwise, the player wins.\n\n' +
                    '⚖️ Fairness: The drawn amount of bounty for each player is generated by on-chain random numbers.\n\n' +
                    '🆓 Free: bombfun.com does not charge any fees.\n\n',
                links: {
                    actions: [
                        {
                            label: 'Create',
                            href: `${this.appConfig.actionInfo.hostname}/box/mystery/create/{amount}/{bomb-number}`,
                            parameters: [
                                {
                                    name: 'bomb-number',
                                    label: 'Enter a bomb number (0-9)',
                                    required: true,
                                },
                                {
                                    type: 'radio',
                                    name: 'amount',
                                    label: 'Bounty amount in SOL',
                                    required: true,
                                    options: [
                                        { label: '0.1 SOL', value: '0.1' },
                                        { label: '0.5 SOL', value: '0.5' },
                                        { label: '1 SOL', value: '1' },
                                    ],
                                },
                            ],
                        },
                    ],
                },
            } as any;
            return payload;
        }
    async grabMysteryBoxAction(id: bigint): Promise<ActionGetResponseDto> {
            let mysteryBox = await this.mysteryBoxDbService.findOne({ id, status: MoreThanOrEqual(MysteryBoxStatus.GRABBING) }, {
                grabMysteryBoxs: true,
            });
            if (!mysteryBox) {
                this.logger.warn(`[grabMysteryBoxAction] MysteryBoxEntity with id ${id} not found`);
                return this.createMysteryBoxAction();
            }
            const amount = Number(BigInt(mysteryBox.amount)) / LAMPORTS_PER_SOL;
            const icon = 'https://storage.bombfun.com/container-2.png';
            const title = `[Get ${amount} SOL] in the Bomb Box`;
            const label = 'Open';
            const { description, disabled } = this.formatGrabPayloadDescription(mysteryBox, amount);
            let payload = {
                icon,
                label,
                title,
                description,
                links: {
                    actions: [
                        {
                            label,
                            href: `${this.appConfig.actionInfo.hostname}/box/mystery/grab/${id}`,
                        },
                    ],
                },
            };
            return disabled ? ({ icon, label, title, description, disabled } as any) : (payload as any);
        }
    formatGrabPayloadDescription(mysteryBox: MysteryBoxEntity, amount: number): {
        description: string;
        disabled: boolean;
    } {
            let playerList = mysteryBox.grabMysteryBoxs
                .filter((grab) => grab.status >= GrabTransactionStatus.CONFIRMED)
                .map((grab) => shortenAddress(grab.senderAddress));
            let player = playerList
                .map((address, index) => `${index + 1}. [💵] ${address}`)
                .join('\n');
            let disabled = false;
            const endTime = formatCountdown(mysteryBox.grabStartTime, 2);
            const baseDescription = `🎁 Bounty amount: ${amount} SOL\n💣 Bomb number: ${mysteryBox.bombNumber}\n🕹 Bombed payout rate: 1.8x\n\n----- Player Details -----`;
            if (!endTime || mysteryBox.status > MysteryBoxStatus.GRABBING) {
                return this.formatEndedMysteryBoxDescription(mysteryBox, amount, baseDescription);
            }
            let description = `${baseDescription}\n\n${player}\n\n♻️Opened: ${mysteryBox.openCount}/${mysteryBox.openLimit}\n⏰ Ends in: ${endTime}`;
            return { description, disabled };
        }
    formatEndedMysteryBoxDescription(mysteryBox: any, amount: any, baseDescription: any) {
            const decimalAmount = new Decimal(amount);
            const decimalPledgeAmount = decimalAmount.times(1.8);
            const lamportsPerSol = new Decimal(LAMPORTS_PER_SOL);
            let totalDistribution = new Decimal(0);
            const playerList = mysteryBox.grabMysteryBoxs
                .filter((grab: any) => grab.status >= GrabTransactionStatus.DISTRIBUTE_INIT)
                .map((grab: any) => {
                const lotteryDrawAmount = calculatePlayerReward(grab.lotteryDrawAmount ? grab.lotteryDrawAmount : '0', decimalPledgeAmount);
                const address = grab.isBomb
                    ? `${shortenAddress(grab.senderAddress)}💣`
                    : shortenAddress(grab.senderAddress);
                totalDistribution = totalDistribution.plus(lotteryDrawAmount);
                return { lotteryDrawAmount, address };
            });
            const formattedPlayerList = playerList
                .map(({ lotteryDrawAmount, address }: { lotteryDrawAmount: any; address: any }, index: number) => `${index + 1}. [💵] ${lotteryDrawAmount.toFixed(2)} ${address}`)
                .join('\n');
            const bounty = calculateBounty(decimalAmount, new Decimal(mysteryBox.lotteryDrawAmount ? mysteryBox.lotteryDrawAmount : 0).div(lamportsPerSol));
            const unclaimedAmount = Decimal.max(0, decimalAmount.minus(totalDistribution));
            const description = `${baseDescription}\n\n${formattedPlayerList}\n\n💸 Profit for box creator: ${bounty.toFixed(2)} SOL\n\n♻️ [${playerList.length}/${this.appConfig.actionInfo.totalBoxCount}] Bounty unclaimed: ${unclaimedAmount.toFixed(2)} SOL\n\n🎯 This Bomb Box is ended. Create a new one at bombfun.com
      `.trim();
            return { description, disabled: true };
        }
}
