//! Protobuf bindings generated by `build.rs` via `tonic-build`.
//!
//! Namespaces are kept identical to the closed-source binary so any
//! side-by-side reading with the reverse-engineered symbols is trivial:
//!
//! | Proto package              | Rust module                            |
//! |---------------------------|----------------------------------------|
//! | `sf.substreams.v1`        | `crate::pb::sf::substreams::v1`        |
//! | `sf.substreams.rpc.v2`    | `crate::pb::sf::substreams::rpc::v2`   |
//! | `sf.firehose.v2`          | `crate::pb::sf::firehose::v2`          |

pub mod sf {
    pub mod substreams {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/sf.substreams.v1.rs"));
        }
        pub mod rpc {
            pub mod v2 {
                include!(concat!(env!("OUT_DIR"), "/sf.substreams.rpc.v2.rs"));
            }
        }
    }
    pub mod firehose {
        pub mod v2 {
            include!(concat!(env!("OUT_DIR"), "/sf.firehose.v2.rs"));
        }
    }
    pub mod solana {
        pub mod dex {
            pub mod trades {
                pub mod v1 {
                    include!(concat!(env!("OUT_DIR"), "/sf.solana.dex.trades.v1.rs"));
                }
            }
        }
    }
}
